<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::create('options', function (Blueprint $table) {
            $table->id();
            $table->string('code', 50);
            $table->string('label', 75);
            $table->string('reference', 50)->comment('La chiave di ricerca dei valori da visualizzare');
            $table->string('icon', 50)->nullable()->comment('codice fontawesome per eventuale icona da visualizzare');
            $table->string('class', 75)->nullable()->comment('classe eventualmente applicata allo stato ed al sue elemento');
            $table->tinyInteger('is_enabled')->default(1);
            $table->timestamp('created_at')->nullable();
            $table->timestamp('updated_at')->nullable();
            $table->index('code', 'options_code_index');
            $table->unique(['code', 'reference'], 'options_code_reference_unique');
            $table->index('label', 'options_label_index');
            $table->unique(['label', 'reference'], 'options_label_reference_unique');
        });

        // Seed data
        DB::table('options')->insert([
            [
                'id' => 1,
                'code' => 'cancel',
                'label' => 'Annulla/Disabilita',
                'reference' => 'DELETE',
                'icon' => null,
                'class' => null,
                'is_enabled' => 1,
                'created_at' => '2021-07-20 10:42:26',
                'updated_at' => '2021-07-20 10:42:26',
            ],
            [
                'id' => 2,
                'code' => 'destroy',
                'label' => 'Elimina da DB',
                'reference' => 'DELETE',
                'icon' => null,
                'class' => null,
                'is_enabled' => 1,
                'created_at' => '2021-07-20 10:42:26',
                'updated_at' => '2021-07-20 10:42:26',
            ],
            [
                'id' => 3,
                'code' => '0',
                'label' => 'Disabled',
                'reference' => 'ED',
                'icon' => null,
                'class' => 'text-danger font-weight-bolder',
                'is_enabled' => 1,
                'created_at' => '2021-06-17 10:42:26',
                'updated_at' => '2021-06-17 10:42:26',
            ],
            [
                'id' => 4,
                'code' => '1',
                'label' => 'Enabled',
                'reference' => 'ED',
                'icon' => null,
                'class' => 'text-success font-weight-bolder',
                'is_enabled' => 1,
                'created_at' => '2021-06-17 10:42:26',
                'updated_at' => '2021-06-17 10:42:26',
            ],
            [
                'id' => 5,
                'code' => '1',
                'label' => 'Gennaio',
                'reference' => 'MONTH',
                'icon' => null,
                'class' => null,
                'is_enabled' => 1,
                'created_at' => '2021-07-02 13:42:26',
                'updated_at' => '2021-07-02 13:42:26',
            ],
            [
                'id' => 6,
                'code' => '2',
                'label' => 'Febbraio',
                'reference' => 'MONTH',
                'icon' => null,
                'class' => null,
                'is_enabled' => 1,
                'created_at' => '2021-07-02 13:42:26',
                'updated_at' => '2021-07-02 13:42:26',
            ],
            [
                'id' => 7,
                'code' => '3',
                'label' => 'Marzo',
                'reference' => 'MONTH',
                'icon' => null,
                'class' => null,
                'is_enabled' => 1,
                'created_at' => '2021-07-02 13:42:26',
                'updated_at' => '2021-07-02 13:42:26',
            ],
            [
                'id' => 8,
                'code' => '4',
                'label' => 'Aprile',
                'reference' => 'MONTH',
                'icon' => null,
                'class' => null,
                'is_enabled' => 1,
                'created_at' => '2021-07-02 13:42:26',
                'updated_at' => '2021-07-02 13:42:26',
            ],
            [
                'id' => 9,
                'code' => '5',
                'label' => 'Maggio',
                'reference' => 'MONTH',
                'icon' => null,
                'class' => null,
                'is_enabled' => 1,
                'created_at' => '2021-07-02 13:42:26',
                'updated_at' => '2021-07-02 13:42:26',
            ],
            [
                'id' => 10,
                'code' => '6',
                'label' => 'Giugno',
                'reference' => 'MONTH',
                'icon' => null,
                'class' => null,
                'is_enabled' => 1,
                'created_at' => '2021-07-02 13:42:26',
                'updated_at' => '2021-07-02 13:42:26',
            ],
            [
                'id' => 11,
                'code' => '7',
                'label' => 'Luglio',
                'reference' => 'MONTH',
                'icon' => null,
                'class' => null,
                'is_enabled' => 1,
                'created_at' => '2021-07-02 13:42:26',
                'updated_at' => '2021-07-02 13:42:26',
            ],
            [
                'id' => 12,
                'code' => '8',
                'label' => 'Agosto',
                'reference' => 'MONTH',
                'icon' => null,
                'class' => null,
                'is_enabled' => 1,
                'created_at' => '2021-07-02 13:42:26',
                'updated_at' => '2021-07-02 13:42:26',
            ],
            [
                'id' => 13,
                'code' => '9',
                'label' => 'Settembre',
                'reference' => 'MONTH',
                'icon' => null,
                'class' => null,
                'is_enabled' => 1,
                'created_at' => '2021-07-02 13:42:26',
                'updated_at' => '2021-07-02 13:42:26',
            ],
            [
                'id' => 14,
                'code' => '10',
                'label' => 'Ottobre',
                'reference' => 'MONTH',
                'icon' => null,
                'class' => null,
                'is_enabled' => 1,
                'created_at' => '2021-07-02 13:42:26',
                'updated_at' => '2021-07-02 13:42:26',
            ],
            [
                'id' => 15,
                'code' => '11',
                'label' => 'Novembre',
                'reference' => 'MONTH',
                'icon' => null,
                'class' => null,
                'is_enabled' => 1,
                'created_at' => '2021-07-02 13:42:26',
                'updated_at' => '2021-07-02 13:42:26',
            ],
            [
                'id' => 16,
                'code' => '12',
                'label' => 'Dicembre',
                'reference' => 'MONTH',
                'icon' => null,
                'class' => null,
                'is_enabled' => 1,
                'created_at' => '2021-07-02 13:42:26',
                'updated_at' => '2021-07-02 13:42:26',
            ],
            [
                'id' => 17,
                'code' => 'string',
                'label' => 'String',
                'reference' => 'TYPECOLS',
                'icon' => null,
                'class' => null,
                'is_enabled' => 1,
                'created_at' => '2021-06-24 10:42:26',
                'updated_at' => '2021-06-24 10:42:26',
            ],
            [
                'id' => 18,
                'code' => 'int',
                'label' => 'Int',
                'reference' => 'TYPECOLS',
                'icon' => null,
                'class' => null,
                'is_enabled' => 1,
                'created_at' => '2021-06-24 10:42:26',
                'updated_at' => '2021-06-24 10:42:26',
            ],
            [
                'id' => 19,
                'code' => 'date',
                'label' => 'Date',
                'reference' => 'TYPECOLS',
                'icon' => null,
                'class' => null,
                'is_enabled' => 1,
                'created_at' => '2021-06-24 10:42:26',
                'updated_at' => '2021-06-24 10:42:26',
            ],
            [
                'id' => 20,
                'code' => 'dateTime',
                'label' => 'DateTime',
                'reference' => 'TYPECOLS',
                'icon' => null,
                'class' => null,
                'is_enabled' => 1,
                'created_at' => '2021-06-24 10:42:26',
                'updated_at' => '2021-06-24 10:42:26',
            ],
        ]);

        DB::table('options')->insert([
            [
                'id' => 21,
                'code' => 'enum',
                'label' => 'Enum',
                'reference' => 'TYPECOLS',
                'icon' => null,
                'class' => null,
                'is_enabled' => 1,
                'created_at' => '2021-06-24 10:42:26',
                'updated_at' => '2021-06-24 10:42:26',
            ],
            [
                'id' => 22,
                'code' => 'currency',
                'label' => 'Currency',
                'reference' => 'TYPECOLS',
                'icon' => null,
                'class' => null,
                'is_enabled' => 1,
                'created_at' => '2021-07-24 10:42:26',
                'updated_at' => '2021-07-24 10:42:26',
            ],
            [
                'id' => 23,
                'code' => 'integer',
                'label' => 'Nr intero',
                'reference' => 'TYPECOLS',
                'icon' => null,
                'class' => null,
                'is_enabled' => 1,
                'created_at' => '2022-12-24 10:42:26',
                'updated_at' => '2022-12-24 10:42:26',
            ],
            [
                'id' => 24,
                'code' => 'float',
                'label' => 'Nr decimale',
                'reference' => 'TYPECOLS',
                'icon' => null,
                'class' => null,
                'is_enabled' => 1,
                'created_at' => '2022-12-24 10:42:26',
                'updated_at' => '2022-12-24 10:42:26',
            ],
            [
                'id' => 25,
                'code' => 'percent',
                'label' => 'Percentuale',
                'reference' => 'TYPECOLS',
                'icon' => null,
                'class' => null,
                'is_enabled' => 1,
                'created_at' => '2022-12-24 10:42:26',
                'updated_at' => '2022-12-24 10:42:26',
            ],
            [
                'id' => 26,
                'code' => 'array',
                'label' => 'Multi valore',
                'reference' => 'TYPECOLS',
                'icon' => null,
                'class' => null,
                'is_enabled' => 1,
                'created_at' => '2023-08-30 10:42:26',
                'updated_at' => '2023-08-31 09:28:19',
            ],
            [
                'id' => 27,
                'code' => 'alert',
                'label' => 'Alert',
                'reference' => 'TYPECOLS',
                'icon' => null,
                'class' => null,
                'is_enabled' => 1,
                'created_at' => '2021-07-24 10:42:26',
                'updated_at' => '2021-07-24 10:42:26',
            ],
            [
                'id' => 28,
                'code' => 'link',
                'label' => 'Link',
                'reference' => 'TYPECOLS',
                'icon' => null,
                'class' => null,
                'is_enabled' => 1,
                'created_at' => '2021-07-07 10:42:26',
                'updated_at' => '2021-07-07 10:42:26',
            ],
            [
                'id' => 29,
                'code' => 'relations',
                'label' => 'Stringa valori model',
                'reference' => 'TYPECOLS',
                'icon' => null,
                'class' => null,
                'is_enabled' => 1,
                'created_at' => '2021-06-24 10:42:26',
                'updated_at' => '2021-06-24 10:42:26',
            ],
            [
                'id' => 30,
                'code' => 'switch',
                'label' => 'Switch',
                'reference' => 'TYPECOLS',
                'icon' => null,
                'class' => null,
                'is_enabled' => 1,
                'created_at' => '2021-06-24 10:42:26',
                'updated_at' => '2021-06-24 10:42:26',
            ],
            [
                'id' => 31,
                'code' => 'match',
                'label' => 'Confronto dati',
                'reference' => 'TYPECOLS',
                'icon' => null,
                'class' => null,
                'is_enabled' => 1,
                'created_at' => '2021-06-24 10:42:26',
                'updated_at' => '2021-06-24 10:42:26',
            ],
            [
                'id' => 32,
                'code' => 'directLink',
                'label' => 'Link diretto',
                'reference' => 'TYPECOLS',
                'icon' => null,
                'class' => null,
                'is_enabled' => 1,
                'created_at' => '2021-06-24 10:42:26',
                'updated_at' => '2021-06-24 10:42:26',
            ],
            [
                'id' => 33,
                'code' => 'text',
                'label' => 'text',
                'reference' => 'TYPEDATA',
                'icon' => null,
                'class' => null,
                'is_enabled' => 1,
                'created_at' => '2021-06-24 10:42:26',
                'updated_at' => '2021-06-24 10:42:26',
            ],
            [
                'id' => 34,
                'code' => 'number',
                'label' => 'number',
                'reference' => 'TYPEDATA',
                'icon' => null,
                'class' => null,
                'is_enabled' => 1,
                'created_at' => '2021-06-24 10:42:26',
                'updated_at' => '2021-06-24 10:42:26',
            ],
            [
                'id' => 35,
                'code' => 'date',
                'label' => 'date',
                'reference' => 'TYPEDATA',
                'icon' => null,
                'class' => null,
                'is_enabled' => 1,
                'created_at' => '2021-06-24 10:42:26',
                'updated_at' => '2021-06-24 10:42:26',
            ],
            [
                'id' => 36,
                'code' => 'select',
                'label' => 'select',
                'reference' => 'TYPEDATA',
                'icon' => null,
                'class' => null,
                'is_enabled' => 1,
                'created_at' => '2021-06-24 10:42:26',
                'updated_at' => '2021-06-24 10:42:26',
            ],
            [
                'id' => 37,
                'code' => 'hidden',
                'label' => 'hidden',
                'reference' => 'TYPEDATA',
                'icon' => null,
                'class' => null,
                'is_enabled' => 1,
                'created_at' => '2021-06-24 10:42:26',
                'updated_at' => '2021-06-24 10:42:26',
            ],
            [
                'id' => 38,
                'code' => 'textarea',
                'label' => 'textarea',
                'reference' => 'TYPEDATA',
                'icon' => null,
                'class' => null,
                'is_enabled' => 1,
                'created_at' => '2021-09-16 10:42:26',
                'updated_at' => '2021-09-16 10:42:26',
            ],
            [
                'id' => 39,
                'code' => 'file',
                'label' => 'file',
                'reference' => 'TYPEDATA',
                'icon' => null,
                'class' => null,
                'is_enabled' => 1,
                'created_at' => '2021-09-17 10:42:26',
                'updated_at' => '2021-09-17 10:42:26',
            ],
            [
                'id' => 40,
                'code' => 'checkbox',
                'label' => 'checkbox',
                'reference' => 'TYPEDATA',
                'icon' => null,
                'class' => null,
                'is_enabled' => 1,
                'created_at' => '2022-03-21 10:42:26',
                'updated_at' => '2022-03-21 10:42:26',
            ],
        ]);

        DB::table('options')->insert([
            [
                'id' => 41,
                'code' => 'button',
                'label' => 'button',
                'reference' => 'TYPEDATA',
                'icon' => null,
                'class' => null,
                'is_enabled' => 1,
                'created_at' => '2022-03-21 10:42:26',
                'updated_at' => '2022-03-21 10:42:26',
            ],
            [
                'id' => 42,
                'code' => 'editable',
                'label' => 'Insert/Edit',
                'reference' => 'TYPEFORM',
                'icon' => 'fa fa-edit',
                'class' => 'text-primary',
                'is_enabled' => 1,
                'created_at' => '2021-07-12 10:42:26',
                'updated_at' => '2023-08-31 08:12:08',
            ],
            [
                'id' => 43,
                'code' => 'filter',
                'label' => 'Filter',
                'reference' => 'TYPEFORM',
                'icon' => 'fas fa-search',
                'class' => 'text-danger',
                'is_enabled' => 1,
                'created_at' => '2021-07-12 10:42:26',
                'updated_at' => '2023-08-31 08:11:54',
            ],
            [
                'id' => 44,
                'code' => 'modal',
                'label' => 'Modal',
                'reference' => 'TYPEFORM',
                'icon' => 'far fa-window-maximize',
                'class' => 'text-success',
                'is_enabled' => 1,
                'created_at' => '2021-09-20 22:00:00',
                'updated_at' => '2021-09-20 22:00:00',
            ],
            [
                'id' => 45,
                'code' => 'child',
                'label' => 'Item Child',
                'reference' => 'TYPEFORM',
                'icon' => null,
                'class' => null,
                'is_enabled' => 1,
                'created_at' => '2021-07-12 10:42:26',
                'updated_at' => '2021-07-12 10:42:26',
            ],
            [
                'id' => 46,
                'code' => '0',
                'label' => 'No',
                'reference' => 'YN',
                'icon' => null,
                'class' => 'text-danger font-weight-bolder',
                'is_enabled' => 1,
                'created_at' => '2021-06-17 10:42:26',
                'updated_at' => '2021-06-17 10:42:26',
            ],
            [
                'id' => 47,
                'code' => '1',
                'label' => 'Si',
                'reference' => 'YN',
                'icon' => null,
                'class' => 'text-success font-weight-bolder',
                'is_enabled' => 1,
                'created_at' => '2021-06-17 10:42:26',
                'updated_at' => '2021-06-17 10:42:26',
            ],
            [
                'id' => 48,
                'code' => 'multiselect',
                'label' => 'MultiSelect',
                'reference' => 'TYPEDATA',
                'icon' => null,
                'class' => null,
                'is_enabled' => 1,
                'created_at' => '2026-02-21 10:42:26',
                'updated_at' => '2026-02-21 10:42:26',
            ],
            [
                'id' => 49,
                'code' => 'daterange',
                'label' => 'Date Range',
                'reference' => 'TYPEDATA',
                'icon' => null,
                'class' => null,
                'is_enabled' => 1,
                'created_at' => '2026-02-21 10:42:26',
                'updated_at' => '2026-02-21 10:42:26',
            ],
            [
                'id' => 50,
                'code' => 'crypted',
                'label' => 'Cryptato',
                'reference' => 'TYPEDATA',
                'icon' => null,
                'class' => null,
                'is_enabled' => 1,
                'created_at' => '2021-06-24 10:42:26',
                'updated_at' => '2021-06-24 10:42:26',
            ],
            [
                'id' => 51,
                'code' => 'crypted',
                'label' => 'Cryptato',
                'reference' => 'TYPECOLS',
                'icon' => null,
                'class' => null,
                'is_enabled' => 1,
                'created_at' => '2021-06-24 10:42:26',
                'updated_at' => '2021-06-24 10:42:26',
            ],
        ]);

    }

    public function down(): void
    {
        Schema::dropIfExists('options');
    }
};
